# Generated by Django 4.2.23 on 2025-08-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetTracker_app', '0002_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello',
        ),
    ]
