# Generated by Django 4.2.23 on 2025-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('is_info', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emp_name', models.CharField(max_length=150, null=True)),
                ('emp_code', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('device_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(default=None, max_length=150, null=True)),
                ('asset_name', models.CharField(default=None, max_length=150, null=True)),
                ('employee_id', models.CharField(default=None, max_length=150, null=True)),
                ('employee_name', models.CharField(default=None, max_length=150, null=True)),
                ('is_info', models.CharField(default=None, max_length=150, null=True)),
                ('is_assigned', models.CharField(default='avaliable', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('unique_id', models.AutoField(auto_created=True, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_code', models.CharField(max_length=100)),
                ('employee_email', models.CharField(default=1, max_length=150)),
                ('team_name', models.CharField(default=1, max_length=150)),
                ('employee_contact', models.IntegerField(default=1, max_length=10)),
                ('employee_password', models.CharField(default=1, max_length=20)),
                ('employee_department', models.CharField(default=1, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('repair_tool_id', models.CharField(max_length=150)),
                ('repair_cost', models.CharField(default='--', max_length=100, null=True)),
                ('return_date', models.DateField(null=True)),
                ('tool_user', models.CharField(max_length=150, null=True)),
                ('tool_user_id', models.CharField(max_length=150, null=True)),
                ('repair_person', models.CharField(max_length=150)),
                ('repair_status', models.CharField(default=1, max_length=150)),
                ('repair_created_at', models.DateField(auto_now_add=True)),
                ('repair_created_by', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='superuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
                ('tool_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_category', models.CharField(max_length=150)),
                ('tool_assigned', models.CharField(max_length=150, null=True)),
                ('assigned_employee_id', models.CharField(max_length=150, null=True)),
                ('tool_avaliability', models.CharField(default='Avaliable', max_length=10)),
                ('tool_company', models.CharField(default='--', max_length=150, null=True)),
                ('tool_model', models.CharField(default='--', max_length=150, null=True)),
                ('tool_purchase', models.CharField(max_length=150, null=True)),
                ('tool_warantty', models.CharField(max_length=150, null=True)),
                ('tool_condition', models.CharField(max_length=150, null=True)),
                ('tool_price', models.IntegerField(default=-1, max_length=150, null=True)),
                ('tool_supplier', models.CharField(max_length=150, null=True)),
                ('tool_invoice', models.IntegerField(max_length=150, null=True)),
                ('tool_location', models.CharField(default='--', max_length=150, null=True)),
                ('tool_remark', models.CharField(default='--', max_length=150, null=True)),
                ('tool_assigneddate', models.DateField(null=True)),
                ('tool_type', models.CharField(default=1, max_length=150, null=True)),
                ('repair_status', models.CharField(default='Not In Repair', max_length=150, null=True)),
            ],
        ),
    ]
